In [12]:
from sqlalchemy import MetaData

from cyclops.query import gemini
from cyclops.query.interface import QueryInterface
from cyclops.query.util import (
    DBSchema,
    DBTable
)

In [19]:
dir(gemini._db.ods)

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'care_site',
 'cdm_source',
 'cohort',
 'cohort_definition',
 'concept',
 'concept_ancestor',
 'concept_class',
 'concept_relationship',
 'concept_synonym',
 'condition_era',
 'condition_occurrence',
 'cost',
 'data',
 'death',
 'device_exposure',
 'domain',
 'dose_era',
 'drug_era',
 'drug_exposure',
 'drug_strength',
 'episode',
 'episode_event',
 'fact_relationship',
 'lkp_concept_map',
 'lkp_variables',
 'location',
 'measurement',
 'name',
 'note',
 'note_nlp',
 'observation',
 'observation_period',
 'payer_plan_period',
 'person',
 'procedure_occurrence',
 'provider',
 'relationship',
 'source_to_concept_map',
 'specimen',
 'visit_detail',
 'visit_occurrence',
 'vocabulary']

In [16]:
visit_occurrence_table = QueryInterface(gemini._db, gemini._db.ods.visit_occurrence)
visit_occurrence_table.run()
visit_occurrence_table.data

2022-06-14 14:46:58,459 INFO cyclops.orm     - Query returned successfully!
2022-06-14 14:46:58,462 INFO cyclops.utils.profile - Finished executing function run_query in 11.778562 s

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_datetime,visit_end_date,visit_end_datetime,visit_type_concept_id,provider_id,care_site_id,...,discharged_to_concept_id,discharged_to_source_value,preceding_visit_occurrence_id,source_file,processed_date,processed_by,hospital_id,username,rowid,cdc_key
0,187880,2,9201,2010-08-20,2010-08-20 23:38:00,2010-08-21,2010-08-21 10:40:00,32817,1719.0,82,...,0,None,30956.0,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,THPM,amirshahif,363444,{'genc_id_code': '15782167'}
1,283196,2,9201,2012-03-19,2012-03-19 17:53:00,2012-03-22,2012-03-22 09:45:00,32817,2451.0,82,...,0,None,187880.0,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,THPM,amirshahif,340009,{'genc_id_code': '15619617'}
2,324473,3,9201,2015-10-12,2015-10-12 12:10:00,2015-10-16,2015-10-16 13:32:00,32817,3057.0,82,...,0,4755,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,THPM,amirshahif,275586,{'genc_id_code': '15171180'}
3,142201,4,9201,2016-07-06,2016-07-06 21:06:00,2016-07-21,2016-07-21 16:00:00,32817,5962.0,79,...,0,None,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SMH,amirshahif,1093,{'genc_id_code': '11119174'}
4,145662,4,9201,2016-07-23,2016-07-23 14:52:00,2016-08-23,2016-08-23 08:11:00,32817,3907.0,79,...,0,4808,142201.0,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SMH,amirshahif,28697,{'genc_id_code': '11622063'}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394914,150316,274478,9201,2017-04-30,2017-04-30 02:00:00,2017-05-01,2017-05-01 23:00:00,32817,454.0,27,...,0,None,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SBK,amirshahif,65479,{'genc_id_code': '12312884'}
394915,90197,274479,9201,2012-03-13,2012-03-13 06:23:00,2012-04-25,2012-04-25 10:40:00,32817,4389.0,82,...,0,4758,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,THPM,amirshahif,371557,{'genc_id_code': '15838637'}
394916,3929,274480,9201,2016-09-09,2016-09-09 20:00:00,2016-09-10,2016-09-10 11:00:00,32817,259.0,27,...,0,None,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SBK,amirshahif,78316,{'genc_id_code': '12489113'}
394917,349829,274481,9201,2016-07-26,2016-07-26 18:00:00,2016-07-28,2016-07-28 13:00:00,32817,5187.0,27,...,0,None,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SBK,amirshahif,83508,{'genc_id_code': '12559339'}
394918,294508,274482,9201,2014-04-10,2014-04-10 18:00:00,2014-04-12,2014-04-12 00:00:00,32817,3520.0,79,...,0,None,NaN,clean_v1_4_0,2022-05-02 18:52:46.328086,172.17.1.86/32,SMH,amirshahif,36053,{'genc_id_code': '11753555'}

In [27]:
measurement_table = QueryInterface(gemini._db, gemini._db.ods.measurement)
measurement_table.run(limit=1000)
measurement_table.data

2022-06-14 14:57:54,984 INFO cyclops.orm     - Query returned successfully!
2022-06-14 14:57:54,987 INFO cyclops.utils.profile - Finished executing function run_query in 0.026158 s

,measurement_id,person_id,measurement_concept_id,measurement_date,measurement_datetime,measurement_time,measurement_type_concept_id,operator_concept_id,value_as_number,value_as_concept_id,...,value_source_value,measurement_event_id,meas_event_field_concept_id,source_file,processed_date,processed_by,hospital_id,username,rowid,cdc_key
0,122279,130015,4158771,2018-10-15,2018-10-15 04:47:00,None,32817,None,None,21498112.0,...,3:Urgent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,THPM,amirshahif,263225,"{'genc_id_code': '15262577', 'triage_level': '..."
1,122280,130048,4158771,2019-08-23,2019-08-23 17:13:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,SMH,amirshahif,27644,"{'genc_id_code': '11657432', 'triage_level': '..."
2,122281,130053,4158771,2013-07-27,2013-07-27 14:59:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,UHNTG,amirshahif,115937,"{'genc_id_code': '13198304', 'triage_level': '..."
3,122282,130053,4158771,2011-01-26,2011-01-26 15:00:00,None,32817,None,None,21498112.0,...,3:Urgent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,SMH,amirshahif,44081,"{'genc_id_code': '11990297', 'triage_level': '..."
4,122283,130085,4158771,2017-08-27,2017-08-27 13:14:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,THPC,amirshahif,320269,"{'genc_id_code': '15708525', 'triage_level': '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,123274,142291,4158771,2019-07-17,2019-07-17 21:57:00,None,32817,None,None,NaN,...,RESUSCITATION,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,SBK,amirshahif,94265,"{'genc_id_code': '12836504', 'triage_level': '..."
996,123275,142302,4158771,2012-04-10,2012-04-10 14:00:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,SBK,amirshahif,78208,"{'genc_id_code': '12597937', 'triage_level': '..."
997,123276,142306,4158771,2011-01-24,2011-01-24 22:56:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,THPM,amirshahif,329165,"{'genc_id_code': '15777047', 'triage_level': '..."
998,123277,142352,4158771,2015-05-08,2015-05-08 13:44:00,None,32817,None,None,21498855.0,...,2:Emergent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,UHNTW,amirshahif,166891,"{'genc_id_code': '13658064', 'triage_level': '..."
999,123278,142353,4158771,2018-05-14,2018-05-14 00:15:00,None,32817,None,None,21498112.0,...,3:Urgent,None,None,clean_v1_4_0,2022-05-03 14:43:47.869964,172.17.1.172/32,UHNTW,amirshahif,202035,"{'genc_id_code': '13979440', 'triage_level': '..."

In [28]:
lkup = QueryInterface(gemini._db, gemini._db.ods.concept)
lkup.run(limit=1000)
lkup.data

2022-06-14 15:19:57,167 INFO cyclops.orm     - Query returned successfully!
2022-06-14 15:19:57,170 INFO cyclops.utils.profile - Finished executing function run_query in 0.270436 s

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,0,No matching concept,Metadata,None,Undefined,None,No matching concept,1970-01-01,2099-12-31,None
1,1,Domain,Metadata,Domain,Domain,None,OMOP generated,1970-01-01,2099-12-31,None
2,2,Gender,Metadata,Domain,Domain,None,OMOP generated,1970-01-01,2099-12-31,None
3,3,Race,Metadata,Domain,Domain,None,OMOP generated,1970-01-01,2099-12-31,None
4,4,Ethnicity,Metadata,Domain,Domain,None,OMOP generated,1970-01-01,2099-12-31,None
...,...,...,...,...,...,...,...,...,...,...
995,9481,circle,Unit,UCUM,Unit,S,circ,1970-01-01,2099-12-31,None
996,9482,centiliter,Unit,UCUM,Unit,S,cL,1970-01-01,2099-12-31,None
997,9483,square centimeter,Unit,UCUM,Unit,S,cm2,1970-01-01,2099-12-31,None
998,9484,degree,Unit,UCUM,Unit,S,deg,1970-01-01,2099-12-31,None
999,9485,decigram,Unit,UCUM,Unit,S,dg,1970-01-01,2099-12-31,None